settings:
  legacy:
    force: false
    interval: 100ms
server:
  status: false
  open: false
  port: 5002
  host: localhost
schema:
- name: proxyMaker
  path: .
  commands: 
    run: 
        status: true
  watcher:
    paths:
    - /
    extensions:
    - go
    ignored_paths:
    - .git
    - .realize
    - vendor
