name: 'proxyMaker'
version: 0.0.1
description: An absolute bare-bones web app.
#author: Your Name <email@example.com>
#homepage: https://www.example.com

web:
    compiler:
        debug: dartdevc

environment:
  sdk: '>=2.0.0 <2.3.0'

dev_dependencies:
  build_runner:
  build_web_compilers:

dependencies:
  usage:

transformers:
